### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by silvioantonio** [silvioantonio/suport-center-xmpp#1]
## Principais bugs do protejo
- [x] Erro ao iniciar aplicação: retorno *null*

>Após avançar em cada etapa, novos bugs irão surgir, 
>assim como novos objetivos

**Comment by manoelcampos** [comment]
O problema foi em um lugar inacreditável. Demorei pra descobrir.
Como vi que teu código tava correto, imaginei que era problema com codificação de caracteres (pois o erro era na classe Base64, que codificada dados binários em uma representação textual).
Mas teu pom.xml tava definindo que o projeto usava UTF8, teus arquivos Java estavam como UTF8.

Então pensei que o problema só poderia ser nas dependências que você incluiu. Ao verificar, vi que vc incluiu a tag ` <type>jar</type>` em cada dependência. De fato nunca usei tal tag, e olha que já uso Maven há muitos anos. Ela faria todo o sentido pois essa biblioteca é baixada como um pacote jar, mas  basta excluir a tag de todas as dependências que tudo funciona.

Não faço ideia qual a lógica, mas no momento que vi a tag, já achei estranho pois nunca precisei incluí-la para nenhum tipo de projeto Maven, seja web ou não.

**Comment by silvioantonio** [comment]
caramba professor que erro foi esse kkkk
mas essa tag foi incluida pelo proprio maven.
eu atualizei minha IDE pra 11.0 e depois disso varios bugs apareceram, nesse exato momento estou voltando pra versao 8.2 que aparentemente é mais estavel e segura...
muito obrigado por achar esse bug pra min rsrsrs

________________________________
De: Manoel Campos da Silva Filho <notifications@github.com>
Enviado: sexta-feira, 17 de maio de 2019 21:59
Para: silvioantonio/suport-center-xmpp
Cc: Silvio Antonio de Oliveira Junior; Author
Assunto: Re: [silvioantonio/suport-center-xmpp] Bugs (#1)


O problema foi em um lugar inacreditável. Demorei pra descobrir.
Como vi que teu código tava correto, imaginei que era problema com codificação de caracteres (pois o erro era na classe Base64, que codificada dados binários em uma representação textual).
Mas teu pom.xml tava definindo que o projeto usava UTF8, teus arquivos Java estavam como UTF8.

Então pensei que o problema só poderia ser nas dependências que você incluiu. Ao verificar, vi que vc incluiu a tag <type>jar</type> em cada dependência. De fato nunca usei tal tag, e olha que já uso Maven há muitos anos. Ela faria todo o sentido pois essa biblioteca é baixada como um pacote jar, mas basta excluir a tag que tudo funciona.

Não faço ideia qual a lógica, mas no momento que vi a tag, já achei estranho pois nunca precisei incluí-la para nenhum tipo de projeto Maven, seja web ou não.

**Comment by manoelcampos** [comment]
Pois é, sinistro. Nunca tinha visto isso.
O problema que tenho tido, que independe de IDE é quanto a versão do Java instalada. O NetBeans depende do Java 8, mas permite criar projetos com versões mais novas do Java. Eu tenho o Java 8 e 12 instalados. Aí, pra projetos maven, se seu projeto usava Java 9 ou superior, a forma de indicar a versão do Java no pom.xml mudou.

Tem que ver quais os problemas q vc tá tendo, se são os mesmos.
As versões mais novas do Java tem incluído recursos fantásticos. 
O que mais gosto é a inferência de tipos, que permite declarar variáveis locais como; 
```java
var listaClientes = new ArrayList<Cliente>();
```

Com isto, não temos que indicar o tipo ao declarar a variável, pois já estamos inicializando a mesma e o compilador descobre o tipo automaticamente.

E isto não é a mesma coisa que tipagem dinâmica do JS, onde lá eu posso trocar o tipo da variável a hora que quiser. No java, se eu atribui uma lista, não terei como mudar o tipo depois de ter atribuído. Java continua dando segurança de tipos sendo estática e fortemente tipada.
